export const SET_CAROUSEL = 'SET_CAROUSEL';
export const SET_DANH_SACH_PHIM = 'SET_DANH_SACH_PHIM'
export const SET_FILM_DANG_CHIEU = 'SET_FILM_DANG_CHIEU'
export const SET_FILM_SAP_CHIEU = 'SET_FILM_SAP_CHIEU';
export const SET_HE_THONG_RAP_CHIEU = 'SET_HE_THONG_RAP_CHIEU';